### ISSUE TITLE
Upgrading to version 3.9.0 is breaking next js app

### ISSUE THREAD

**Issue by AkMo3** [ObserveRTC/client-monitor-js#32] opened 2024-04-30 10:20 UTC
Problem:
We are using client-monitor-js in our internal observer package. Recently, we upgrade this package to use the `3.9.0` version. 

This interval package is used in our next web app. After the upgrade we are facing error with message `TypeError: Cannot read properties of undefined (reading 'getUserMedia')`. Ref:

<img width="589" alt="image" src="https://github.com/ObserveRTC/client-monitor-js/assets/69365878/7e342268-ae17-47c0-8a89-c6808fccfc0f">

On reading docs, we added the parameter `integrateNavigatorMediaDevices: false` to config and everything works well. But, on doing this I loose use media error events.

Expected:
I can use the package without providing the extra configuration.

**Comment by balazskreith** [comment] 2024-04-30 11:20
Thanks for the detailed description.

At any time you can integrate browser `mediaDevices` to an instantiated monitor by calling `ClientMonitor.integrateNavigatorMediaDevices(monitor)`, where `monitor` is a `ClientMonitor` instance. Just make sure you call in an app running in the browser.

As for the error, that probably means that the `mediaDevices` property of the navigator is not the one browser [should](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices) provide.

From `3.9.1` there is a check if `getUserMedia` is a function so it fails at creation time if not. But it's not gonna solve your problem. The proper solution is to figure out what's going on next.js, which requires some work to setup a project.

**Comment by balazskreith** [comment] 2024-08-25 06:41
@AkMo3  if the issue is resolved, pls close this Issue

**Closed** 2024-08-26 04:50 UTC
